export { default as Detail } from './Detail'
export { default as Home } from './Home'
export { default as Input } from './Input'
export { default as Loading } from './Loading'
export { default as SignIn } from './SignIn'
export { default as SignUp } from './SignUp'
export { default as Statistics } from './Statistics'
