export default {
  // Page
  INITIAL: 'INITIAL',
  INITIAL_NEXT_BUTTON1: 'INITIAL_NEXT_BUTTON1',
  INITIAL_NEXT_BUTTON2: 'INITIAL_NEXT_BUTTON2',
  INITIAL_NEXT_BUTTON3: 'INITIAL_NEXT_BUTTON3',
  CHOOSE_LOGIN: 'CHOOSE_LOGIN',
  SIGN_IN: 'SIGN_IN',
  SIGN_IN_BTN: 'SIGN_IN_BUTTON',
  SIGN_IN_EMAIL: 'SIGN_IN_EMAIL',
  SIGN_IN_PASSWORD: 'SIGN_IN_PASSWORD',
  SIGN_UP: 'SIGN_UP',
  SIGN_UP_BTN: 'SIGN_UP_BUTTON',
  SIGN_UP_EMAIL: 'SIGN_UP_EMAIL',
  SIGN_UP_PASSWORD: 'SIGN_UP_PASSWORD',
  SIGN_UP_REGISTER_BUTTON: 'SIGN_UP_REGISTER_BUTTON',
  HOME: 'HOME',
}
